# Generated by Django 3.1.4 on 2021-01-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='requiresCorrection',
            field=models.BooleanField(default=False),
        ),
    ]
