# Generated by Django 3.1.4 on 2021-01-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Affiliation Body',
                'verbose_name_plural': 'Affiliation Bodies',
                'db_table': 'affiliation_body',
            },
        ),
        migrations.CreateModel(
            name='AffiliationTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Affiliation Title',
                'verbose_name_plural': 'Affiliation Titles',
                'db_table': 'affiliation_title',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='affiliationBody',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.affiliationbody'),
        ),
        migrations.AddField(
            model_name='user',
            name='affiliationTitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.affiliationtitle'),
        ),
    ]
