# Generated by Django 3.1.4 on 2021-01-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210106_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isIDVerified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='requiresCorrection',
        ),
        migrations.AddField(
            model_name='affiliationbody',
            name='isEducational',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='affiliationtitle',
            name='isJobTitle',
            field=models.BooleanField(default=False),
        ),
    ]
