# Generated by Django 3.1.4 on 2021-01-08 18:31

from django.db import migrations, models
import user.fields
import user.media


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210108_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='IDCard',
            field=user.fields.MediaField(blank=True, null=True, storage=user.media.UserIDStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='isIDVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserIDCard',
        ),
    ]
