# Generated by Django 3.1.4 on 2021-02-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210125_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Student'), (2, 'Academician'), (3, 'Industry'), (4, 'Judge'), (5, 'Press')], null=True),
        ),
    ]
