# Generated by Django 3.1.4 on 2021-02-03 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0012_auto_20210203_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantJudgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('points', models.PositiveSmallIntegerField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judge', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.participant')),
            ],
            options={
                'verbose_name': 'Participant Judgement',
                'verbose_name_plural': 'Participant Judgements',
                'db_table': 'participant_judgement',
                'unique_together': {('judge', 'participant')},
            },
        ),
    ]
