# Generated by Django 3.1.4 on 2021-01-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210108_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
