# Generated by Django 3.1.4 on 2021-01-17 17:50

from django.db import migrations, models
import django.db.models.deletion
import user.fields
import user.media


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210117_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', user.fields.MediaField(blank=True, null=True, storage=user.media.SubmissionStorage(), upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Image'), (2, 'PDF'), (3, 'PPT'), (4, 'Youtube URL')], default=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('isPublic', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.participant')),
            ],
            options={
                'verbose_name': 'Event Submission',
                'verbose_name_plural': 'Event Submissions',
                'db_table': 'submission',
            },
        ),
    ]
