# Generated by Django 3.1.4 on 2021-01-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
    ]
