# Generated by Django 3.1.4 on 2021-01-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210117_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shortDescription',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
