# Generated by Django 3.1.4 on 2021-01-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_shortdescription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('slug', 'parent')},
        ),
    ]
