# Generated by Django 3.1.4 on 2021-01-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20210117_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
