# Generated by Django 3.1.4 on 2021-01-23 13:24

from django.db import migrations, models
import multiselectfield.db.fields
import user.fields
import user.media


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_submission_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='acceptRegistrations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='allowedUserTypes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Admin'), (1, 'Student'), (2, 'Academician'), (3, 'Industry'), (4, 'Judge')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=user.fields.MediaField(blank=True, null=True, storage=user.media.EventStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='registrationCloseTimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Fest'), (1, 'Competition'), (2, 'Workshop')], default=0),
        ),
    ]
