# Generated by Django 3.1.4 on 2021-02-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_eventemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanager',
            name='canJudgeParticipants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmanager',
            name='canSendEmails',
            field=models.BooleanField(default=False),
        ),
    ]
