# Generated by Django 3.1.4 on 2021-02-21 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210221_1725'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0012_auto_20210203_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Other'), (1, 'Zoom'), (2, 'Microsoft Teams'), (3, 'Jitsi')], default=0)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='endTimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='startTimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='allowedUserTypes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Admin'), (1, 'Student'), (2, 'Academician'), (3, 'Industry'), (4, 'Judge'), (5, 'Press')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Fest'), (1, 'Competition'), (2, 'Workshop'), (3, 'Webinar')], default=0),
        ),
        migrations.AlterField(
            model_name='eventemail',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Student'), (2, 'Academician'), (3, 'Industry'), (4, 'Judge'), (5, 'Press')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'team', 'event')},
        ),
        migrations.AddField(
            model_name='event',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.webinarlink'),
        ),
    ]
