# Generated by Django 3.1.4 on 2021-02-21 12:15

from django.db import migrations
import user.fields
import user.media


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20210221_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=user.fields.MediaField(blank=True, null=True, storage=user.media.EventStorage(), upload_to=''),
        ),
    ]
