# Generated by Django 3.1.4 on 2021-02-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_event_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='webinar',
        ),
        migrations.AddField(
            model_name='event',
            name='webinarLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='webinarPlatform',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Other'), (1, 'Zoom'), (2, 'Microsoft Teams'), (3, 'Jitsi')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.DeleteModel(
            name='WebinarLink',
        ),
    ]
