# Generated by Django 3.1.4 on 2021-02-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20210221_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='customFields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
