# Generated by Django 3.1.4 on 2021-02-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_event_customfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requireRegistration',
            field=models.BooleanField(default=True),
        ),
    ]
