# Generated by Django 3.1.4 on 2021-02-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_event_requireregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enableGallery',
            field=models.BooleanField(default=False),
        ),
    ]
