# Generated by Django 3.1.4 on 2021-02-23 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0018_event_enablegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slotLimits',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='eliminator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='feedback',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='timestampEliminated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
