# Generated by Django 3.1.4 on 2021-02-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20210223_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanager',
            name='canEliminateParticipants',
            field=models.BooleanField(default=False),
        ),
    ]
