# Generated by Django 3.1.4 on 2021-02-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_eventmanager_caneliminateparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='prize',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First Place'), (2, 'Second Place'), (3, 'Third Place')], null=True),
        ),
    ]
