# Generated by Django 3.1.4 on 2021-02-17 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.fields
import user.media


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0012_auto_20210203_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampCreated', models.DateTimeField(auto_created=True)),
                ('type', models.PositiveSmallIntegerField(default=0, verbose_name=((0, 'Participation'), (1, 'First Place'), (2, 'Second Place'), (3, 'Third Place')))),
                ('file', user.fields.MediaField(blank=True, null=True, storage=user.media.CertificateStorage(), upload_to='')),
                ('generations', models.PositiveSmallIntegerField(default=1)),
                ('timestampLastGenerated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Certificate',
                'verbose_name_plural': 'Generated Certificates',
                'db_table': 'generated_certificate',
                'unique_together': {('event', 'type', 'participant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(default=0, verbose_name=((0, 'Participation'), (1, 'First Place'), (2, 'Second Place'), (3, 'Third Place')))),
                ('namePositionX', models.PositiveSmallIntegerField(default=0)),
                ('namePositionY', models.PositiveSmallIntegerField(default=0)),
                ('nameFontName', models.CharField(blank=True, max_length=25, null=True)),
                ('nameFontURL', models.URLField(blank=True, null=True)),
                ('nameFontSize', models.PositiveSmallIntegerField(default=16)),
                ('nameFontColor', models.CharField(default='#000', max_length=12)),
                ('isReleased', models.BooleanField(default=True)),
                ('template', user.fields.MediaField(blank=True, null=True, storage=user.media.CertificateTemplateStorage(), upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'verbose_name': 'Event Certificate',
                'verbose_name_plural': 'Event Certificates',
                'db_table': 'event_certificate',
                'unique_together': {('event', 'type')},
            },
        ),
    ]
