# Generated by Django 3.1.4 on 2021-02-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_auto_20210225_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcertificate',
            name='includePrizePosition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='prizePositionX',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='prizePositionY',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventcertificate',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Participation'), (1, 'Merit/Prize')], default=0),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='type',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=((0, 'Participation'), (1, 'Merit/Prize'))),
        ),
    ]
