# Generated by Django 3.1.4 on 2021-02-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_auto_20210226_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcertificate',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Participation'), (1, 'Merit/Prize')], default=0),
        ),
    ]
