# Generated by Django 3.1.4 on 2021-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_auto_20210226_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcertificate',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Participation'), (1, 'Merit/Prize'), (2, 'Volunteer')], default=0),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Participation'), (1, 'Merit/Prize'), (2, 'Volunteer')], default=0),
        ),
    ]
